version: '3.5'

services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - exchange

  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rates_db
    ports:
      - "3306:3306"
    networks:
      - exchange

  currency-provider:
    container_name: currency-provider
    build: ../currency-provider
    environment:
      RABBIT_ADDRESSES: rabbit:5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      RABBIT_RATES_QUEUE_NAME: rates
    depends_on:
      - rabbit
    ports:
      - "8081:8081"
    networks:
      - exchange

  currency-persistence-service:
    container_name: currency-persistence-service
    build: ../currency-persistence-service
    environment:
      RABBIT_ADDRESSES: rabbit:5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      RABBIT_RATES_QUEUE_NAME: rates
      DATABASE_URL: db:3306/rates_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - rabbit
      - db
    ports:
      - "8082:8082"
    networks:
      - exchange

  currency-api:
    container_name: currency-api
    build: ../currency-api
    environment:
      RABBIT_ADDRESSES: rabbit:5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      RABBIT_NOTIFICATION_QUEUE_NAME: notification_queue
      DATABASE_URL: db:3306/rates_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - rabbit
      - db
    ports:
      - "8083:8083"
    networks:
      - exchange

  email-service:
    container_name: email-service
    build: ../email-service
    environment:
      RABBIT_ADDRESSES: rabbit:5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      RABBIT_NOTIFICATION_QUEUE_NAME: notification_queue
      MAIL_HOST_NAME: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: spamkonto018@gmail.com
      MAIL_PASSWORD: "mokf gobw qhcm sbav"
    depends_on:
      - rabbit
    ports:
      - "8084:8084"
    networks:
      - exchange

networks:
  exchange: